### PR TITLE
Add `away_mode` `door_state` `lock_state` `latch_state` to Aqara Lock A100 D200 D100 H100 P100 N100 S100

### PR DESCRIPTION
**Pull request by Necroneco**
- fix res name of `verification failed` for A100
- add a binary_sensor `away mode` for A100 and D200
- add binary sensors **Door State**, **Lock State**, **Latch State** for A100 and D200
  - the **Door State** keep the name `lock` for `LOCK_NOTIFICATION` use. (maybe consider change it to `door_state`)
  - the **Lock State** use `auto locking` and `lock by handle` for clearer description in `LOCK_NOTIFICATION`

---

Other similar locks may also be modified in this way, but I didn't do it because I don't have those device.

### CODE REVIEW

**Comment by niceboygithub** [comment]
Need to consider others lock, like P100, N100 etc.

**Comment by Necroneco** [comment]
> Need to consider others lock, like P100, N100 etc.

These changes are safe for other locks, with no impact.

Do you need me to change other locks as well? I can try to do it but I have no device for test.

**Comment by Necroneco** [comment]
- also added **Away Mode**, **Door State**, **Lock State**, **Latch State** to D100 H100 P100 N100 S100
- renamed key `lock` to `door_state`

only tested on D200 and A100

**Comment by Necroneco** [comment]
keep the `sensor.xxxx_lock` as before, no breaking change.

**Comment by ARoussakov** [comment]
@caibinqing **Aqara Smart Door Lock D100 Lock Event** don't make a diference between unlok from inside or outside. Both hase state **"The door is unlocked"**. But Aqara can make the diffirence, from there it was unlocked. It also has state **"Unlocked with NFC by user"**, but nothing special for Fingerprit. And if case, if only one user use NFC card, **Aqara Smart Door Lock D100 Key Id** state is not changing, and automation with changing this state is not running.

**Comment by caibinqing** [comment]
> **Aqara Smart Door Lock D100 Lock Event** don't make a diference between unlok from inside or outside. Both hase state **"The door is unlocked"**. But Aqara can make the diffirence, from there it was unlocked. It also has state **"Unlocked with NFC by user"**, but nothing special for Fingerprit. And if case, if only one user use NFC card, **Aqara Smart Door Lock D100 Key Id** state is not changing, and automation with changing this state is not running.

Sorry, I don't have a D100, my A100 Pro and D200 can distinguish between **unlock from inside** and **unlock by fingerprint** or **face** (I haven't used NFC)
Perhaps you could double-check the logs? It will change several states quickly.

And there is another way you can have a try, delete lines 54-64 of https://github.com/niceboygithub/AqaraGateway/blob/6a87a5b28f358423257fcbb19292e4425697b22b/custom_components/aqara_gateway/core/lock_data.py#L54-L64

**Comment by ARoussakov** [comment]
Deleted the lines, it was not helpfull. Also checked log file again, it doesn't contains **Aqara Smart Door Lock D100 Lock Event** related to Fingerprit.

**Comment by ARoussakov** [comment]
I have Aqara HUB E1 with custom Firmware. Do you know, maybe it possible to capture some logs on it via Telnet?

**Comment by AntoxaSa** [comment]
> У меня есть Aqara HUB E1 с пользовательской прошивкой. Может быть, вы знаете, как получить доступ к журналам через Telnet?

У вас получилось разобраться? тоже D100, хаб е1 есть с открытм телнет и прокинут в HA

**Pull request merged**
